export const US_METROS = [
  "Remote",
  "San Francisco, CA",
  "New York, NY",
  "Seattle, WA",
  "Los Angeles, CA",
  "Boston, MA",
  "Austin, TX",
  "Chicago, IL",
  "Washington, DC",
  "Denver, CO",
  "Atlanta, GA",
  "San Diego, CA",
  "San Jose, CA",
  "Dallas, TX",
  "Houston, TX",
  "Portland, OR",
  "Philadelphia, PA",
  "Phoenix, AZ",
  "Miami, FL",
  "Raleigh, NC",
  "Charlotte, NC",
  "Minneapolis, MN",
  "Pittsburgh, PA",
  "Salt Lake City, UT",
  "Nashville, TN",
  "Detroit, MI",
  "Tampa, FL",
  "Orlando, FL",
  "St. Louis, MO",
  "Kansas City, MO",
  "Indianapolis, IN",
  "Columbus, OH",
  "Cleveland, OH",
  "Cincinnati, OH",
  "Milwaukee, WI",
  "Las Vegas, NV",
  "Sacramento, CA",
  "Boulder, CO",
  "Richmond, VA",
  "Baltimore, MD",
  "Hartford, CT",
  "Providence, RI",
  "Buffalo, NY",
  "New Orleans, LA",
  "Oklahoma City, OK",
  "Albuquerque, NM",
  "Tucson, AZ",
  "Boise, ID",
  "Madison, WI",
  "Ann Arbor, MI",
  "Des Moines, IA",
  "Omaha, NE",
  "Honolulu, HI",
  "Other",
] as const;
