[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmd = "npm install"

[phases.build]
cmd = "npm run build && echo 'import(\"./production.js\");' > dist/index.js"

[start]
cmd = "node dist/index.js"

[variables]
NODE_ENV = "production"