services:
  - type: web
    name: recrutas
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: recrutas-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: REPLIT_DOMAINS
        sync: false

databases:
  - name: recrutas-db
    databaseName: recrutas
    user: recrutas